export const ADD_SEARCH_RESULTS_SUCCESS = "ADD_SEARCH_RESULTS_SUCCESS";
export const ADD_SEARCH_RESULTS = "ADD_SEARCH_RESULTS";
export const ADD_SEARCH_RESULTS_LATEST = "ADD_SEARCH_RESULTS_LATEST";
export const ADD_SEARCH_RESULTS_FAIL = "ADD_SEARCH_RESULTS_FAIL";
export const ADD_SEARCH_RESULTS_BEGIN = "ADD_SEARCH_RESULTS_BEGIN";
export const USER_LOGOUT = "USER_LOGOUT";
